export const CART_ADD = 'CART_ADD';
export const CART_ADD_START = 'CART_ADD_START';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAILED = 'CART_ADD_FAILED';
export const CART_ADD_CLEAN = 'CART_ADD_CLEAN';

export const CART_REMOVE = 'CART_REMOVE';
export const CART_REMOVE_START = 'CART_REMOVE_START';
export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS';
export const CART_REMOVE_FAILED = 'CART_REMOVE_FAILED';
export const CART_REMOVE_CLEAN = 'CART_REMOVE_CLEAN';

export const CART_LIST_FETCH = 'CART_LIST_FETCH';
export const CART_LIST_FETCH_START = 'CART_LIST_FETCH_START';
export const CART_LIST_FETCH_SUCCESS = 'CART_LIST_FETCH_SUCCESS';
export const CART_LIST_FETCH_FAILED = 'CART_LIST_FETCH_FAILED';
export const CART_LIST_FETCH_CLEAN = 'CART_LIST_FETCH_CLEAN';

export const CART_APPLY_COUPONS = 'CART_APPLY_COUPONS';
export const CART_APPLY_COUPONS_START = 'CART_APPLY_COUPONS_START';
export const CART_APPLY_COUPONS_SUCCESS = 'CART_APPLY_COUPONS_SUCCESS';
export const CART_APPLY_COUPONS_FAILED = 'CART_APPLY_COUPONS_FAILED';
export const CART_APPLY_COUPONS_CLEAN = 'CART_APPLY_COUPONS_CLEAN';

export const CART_REMOVE_COUPONS = 'CART_REMOVE_COUPONS';
export const CART_REMOVE_COUPONS_START = 'CART_REMOVE_COUPONS_START';
export const CART_REMOVE_COUPONS_SUCCESS = 'CART_REMOVE_COUPONS_SUCCESS';
export const CART_REMOVE_COUPONS_FAILED = 'CART_REMOVE_COUPONS_FAILED';
export const CART_REMOVE_COUPONS_CLEAN = 'CART_REMOVE_COUPONS_CLEAN';

export const CART_APPLY_REFERRAL = 'CART_APPLY_REFERRAL';
export const CART_APPLY_REFERRAL_START = 'CART_APPLY_REFERRAL_START';
export const CART_APPLY_REFERRAL_SUCCESS = 'CART_APPLY_REFERRAL_SUCCESS';
export const CART_APPLY_REFERRAL_FAILED = 'CART_APPLY_REFERRAL_FAILED';
export const CART_APPLY_REFERRAL_CLEAN = 'CART_APPLY_REFERRAL_CLEAN';

export const CART_REMOVE_REFERRAL = 'CART_REMOVE_REFERRAL';
export const CART_REMOVE_REFERRAL_START = 'CART_REMOVE_REFERRAL_START';
export const CART_REMOVE_REFERRAL_SUCCESS = 'CART_REMOVE_REFERRAL_SUCCESS';
export const CART_REMOVE_REFERRAL_FAILED = 'CART_REMOVE_REFERRAL_FAILED';
export const CART_REMOVE_REFERRAL_CLEAN = 'CART_REMOVE_REFERRAL_CLEAN';

export const CART_ITEM_CHANGE = 'CART_ITEM_CHANGE';
export const CART_ITEM_CHANGE_START = 'CART_ITEM_CHANGE_START';
export const CART_ITEM_CHANGE_SUCCESS = 'CART_ITEM_CHANGE_SUCCESS';
export const CART_ITEM_CHANGE_FAILED = 'CART_ITEM_CHANGE_FAILED';
export const CART_ITEM_CHANGE_CLEAN = 'CART_ITEM_CHANGE_CLEAN';

export const CART_CREATE_ORDER = 'CART_CREATE_ORDER';
export const CART_CREATE_ORDER_START = 'CART_CREATE_ORDER_START';
export const CART_CREATE_ORDER_SUCCESS = 'CART_CREATE_ORDER_SUCCESS';
export const CART_CREATE_ORDER_FAILED = 'CART_CREATE_ORDER_FAILED';
export const CART_CREATE_ORDER_CLEAN = 'CART_CREATE_ORDER_CLEAN';

export const CART_ONLINE_CHECKOUT = 'CART_ONLINE_CHECKOUT';
export const CART_ONLINE_CHECKOUT_START = 'CART_ONLINE_CHECKOUT_START';
export const CART_ONLINE_CHECKOUT_SUCCESS = 'CART_ONLINE_CHECKOUT_SUCCESS';
export const CART_ONLINE_CHECKOUT_FAILED = 'CART_ONLINE_CHECKOUT_FAILED';
export const CART_ONLINE_CHECKOUT_CLEAN = 'CART_ONLINE_CHECKOUT_CLEAN';

export const CART_OFFLINE_CHECKOUT = 'CART_OFFLINE_CHECKOUT';
export const CART_OFFLINE_CHECKOUT_START = 'CART_OFFLINE_CHECKOUT_START';
export const CART_OFFLINE_CHECKOUT_SUCCESS = 'CART_OFFLINE_CHECKOUT_SUCCESS';
export const CART_OFFLINE_CHECKOUT_FAILED = 'CART_OFFLINE_CHECKOUT_FAILED';

export const CART_CHECKOUT_DONE = 'CART_CHECKOUT_DONE';
export const CART_CHECKOUT_DONE_START = 'CART_CHECKOUT_DONE_START';
export const CART_CHECKOUT_DONE_SUCCESS = 'CART_CHECKOUT_DONE_SUCCESS';
export const CART_CHECKOUT_DONE_FAILED = 'CART_CHECKOUT_DONE_FAILED';
export const CART_CHECKOUT_DONE_CLEAN = 'CART_CHECKOUT_DONE_CLEAN';

export const CART_SYNC = 'CART_SYNC';
export const CART_SYNC_START = 'CART_SYNC_START';
export const CART_SYNC_SUCCESS = 'CART_SYNC_SUCCESS';
export const CART_SYNC_FAILED = 'CART_SYNC_FAILED';
