export const LOGIN = "LOGIN"
export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const SIGNUP = "SIGNUP"
export const SIGNUP_START = "SIGNUP_START"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILED = "SIGNUP_FAILED"

export const RESET_PASSWORD = "RESET_PASSWORT"
export const RESET_PASSWORD_START = "RESET_PASSWORT_START"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORT_SUCCESS"
export const RESET_PASSWORD_FAILED = "RESET_PASSWORT_FAILED"

export const EDIT_PROFILE = "EDIT_PROFILE"
export const EDIT_PROFILE_START = "EDIT_PROFILE_START"
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAILED = "EDIT_PROFILE_FAILED"