export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const ADD_ITEM_TO_CART_START = 'ADD_ITEM_TO_CART_START';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const ADD_ITEM_TO_CART_FAILED = 'ADD_ITEM_TO_CART_FAILED';
export const ADD_ITEM_TO_CART_CLEAN = 'ADD_ITEM_TO_CART_CLEAN';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_ITEM_FROM_CART_START = 'REMOVE_ITEM_FROM_CART_START';
export const REMOVE_ITEM_FROM_CART_SUCCESS = 'REMOVE_ITEM_FROM_CART_SUCCESS';
export const REMOVE_ITEM_FROM_CART_FAILED = 'REMOVE_ITEM_FROM_CART_FAILED';
export const REMOVE_ITEM_FROM_CART_CLEAN = 'REMOVE_ITEM_FROM_CART_CLEAN';