export const FETCH_SUBCATEGORY = "FETCH_SUBCATEGORY"
export const FETCH_SUBCATEGORY_START = "FETCH_SUBCATEGORY_START"
export const FETCH_SUBCATEGORY_SUCCESS = "FETCH_SUBCATEGORY_SUCCESS"
export const FETCH_SUBCATEGORY_FAILED = "FETCH_SUBCATEGORY_FAILED"