export const FETCH_WISHLIST = "FETCH_WISHLIST";
export const FETCH_WISHLIST_START = "FETCH_WISHLIST_START";
export const FETCH_WISHLIST_SUCCESS = "FETCH_WISHLIST_SUCCESS";
export const FETCH_WISHLIST_FAILED = "FETCH_WISHLIST_FAILED"

export const ADD_ITEM_TO_WISHLIST = "ADD_ITEM_TO_WISHLIST";
export const ADD_ITEM_TO_WISHLIST_START = "ADD_ITEM_TO_WISHLIST_START";
export const ADD_ITEM_TO_WISHLIST_SUCCESS = "ADD_ITEM_TO_WISHLIST_SUCCESS";
export const ADD_ITEM_TO_WISHLIST_FAILED = "ADD_ITEM_TO_WISHLIST_FAILED";

export const REMOVE_ITEM_FROM_WISHLIST = "REMOVE_ITEM_FROM_WISHLIST";
export const REMOVE_ITEM_FROM_WISHLIST_START = "REMOVE_ITEM_FROM_WISHLIST_START";
export const REMOVE_ITEM_FROM_WISHLIST_SUCCESS = "REMOVE_ITEM_FROM_WISHLIST_SUCCESS";
export const REMOVE_ITEM_FROM_WISHLIST_FAILED = "REMOVE_ITEM_FROM_WISHLIST_FAILED";

