export const USER_LOGIN = 'USER_LOGIN';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';

export const REGISTER = 'REGISTER';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_CLEAN = 'REGISTER_CLEAN';

export const ACTIVATE = 'ACTIVATE';
export const ACTIVATE_START = 'ACTIVATE_START';
export const ACTIVATE_FAILED = 'ACTIVATE_FAILED';
export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS';

export const FORGOT_PWD = 'FORGOT_PWD';
export const FORGOT_PWD_START = 'FORGOT_PWD_START';
export const FORGOT_PWD_FAILED = 'FORGOT_PWD_FAILED';
export const FORGOT_PWD_SUCCESS = 'FORGOT_PWD_SUCCESS';
export const FORGOT_PWD_CLEAN = 'FORGOT_PWD_CLEAN';

export const RESET_PWD = 'RESET_PWD';
export const RESET_PWD_START = 'RESET_PWD_START';
export const RESET_PWD_FAILED = 'RESET_PWD_FAILED';
export const RESET_PWD_SUCCESS = 'RESET_PWD_SUCCESS';
export const RESET_PWD_CLEAN = 'RESET_PWD_CLEAN';

export const SET_INFO = 'SET_INFO';

export const GET_USER = 'GET_USER';
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const UPDATE_USER_CLEAN = 'UPDATE_USER_CLEAN';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export const DELETE_USER_CLEAN = 'DELETE_USER_CLEAN';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const REMOVE_AVATAR = 'REMOVE_AVATAR';

export const UPLOAD_COVER = 'UPLOAD_COVER';

export const USER_LOGS_FETCH = 'USER_LOGS_FETCH';
export const USER_LOGS_FETCH_START = 'USER_LOGS_FETCH_START';
export const USER_LOGS_FETCH_SUCCESS = 'USER_LOGS_FETCH_SUCCESS';
export const USER_LOGS_FETCH_FAILED = 'USER_LOGS_FETCH_FAILED';

export const USER_BUSINESS_FETCH = 'USER_BUSINESS_FETCH';
export const USER_BUSINESS_FETCH_START = 'USER_BUSINESS_FETCH_START';
export const USER_BUSINESS_FETCH_SUCCESS = 'USER_BUSINESS_FETCH_SUCCESS';
export const USER_BUSINESS_FETCH_FAILED = 'USER_BUSINESS_FETCH_FAILED';

export const USER_BRANCHES_UPDATE = 'USER_BRANCHES_UPDATE';
export const USER_BRANCHES_UPDATE_START = 'USER_BRANCHES_UPDATE_START';
export const USER_BRANCHES_UPDATE_SUCCESS = 'USER_BRANCHES_UPDATE_SUCCESS';
export const USER_BRANCHES_UPDATE_FAILED = 'USER_BRANCHES_UPDATE_FAILED';

export const GET_COMPANY_USERS = 'GET_COMPANY_USERS';
export const GET_COMPANY_USERS_START = 'GET_COMPANY_USERS_START';
export const GET_COMPANY_USERS_SUCCESS = 'GET_COMPANY_USERS_SUCCESS';
export const GET_COMPANY_USERS_FAILED = 'GET_COMPANY_USERS_FAILED';

export const GET_BRANCH_USERS = 'GET_BRANCH_USERS';
export const GET_BRANCH_USERS_START = 'GET_BRANCH_USERS_START';
export const GET_BRANCH_USERS_SUCCESS = 'GET_BRANCH_USERS_SUCCESS';
export const GET_BRANCH_USERS_FAILED = 'GET_BRANCH_USERS_FAILED';

export const GET_BUSINESS_USERS = 'GET_BUSINESS_USERS';
export const GET_BUSINESS_USERS_START = 'GET_BUSINESS_USERS_START';
export const GET_BUSINESS_USERS_SUCCESS = 'GET_BUSINESS_USERS_SUCCESS';
export const GET_BUSINESS_USERS_FAILED = 'GET_BUSINESS_USERS_FAILED';

export const COMPANY_USER_IMPORT = 'COMPANY_USER_IMPORT';
export const COMPANY_USER_IMPORT_START = 'COMPANY_USER_IMPORT_START';
export const COMPANY_USER_IMPORT_SUCCESS = 'COMPANY_USER_IMPORT_SUCCESS';
export const COMPANY_USER_IMPORT_FAILED = 'COMPANY_USER_IMPORT_FAILED';
export const COMPANY_USER_IMPORT_CLEAN = 'COMPANY_USER_IMPORT_CLEAN';

export const COMPANY_USER_EXPORT = 'COMPANY_USER_EXPORT';
export const COMPANY_USER_EXPORT_START = 'COMPANY_USER_EXPORT_START';
export const COMPANY_USER_EXPORT_SUCCESS = 'COMPANY_USER_EXPORT_SUCCESS';
export const COMPANY_USER_EXPORT_FAILED = 'COMPANY_USER_EXPORT_FAILED';
export const COMPANY_USER_EXPORT_CLEAN = 'COMPANY_USER_EXPORT_CLEAN';

export const COMPANY_USER_DOWNLOAD_CSV_TEMPLATE = 'COMPANY_USER_DOWNLOAD_CSV_TEMPLATE';
export const COMPANY_USER_DOWNLOAD_CSV_TEMPLATE_START = 'COMPANY_USER_DOWNLOAD_CSV_TEMPLATE_START';
export const COMPANY_USER_DOWNLOAD_CSV_TEMPLATE_SUCCESS = 'COMPANY_USER_DOWNLOAD_CSV_TEMPLATE_SUCCESS';
export const COMPANY_USER_DOWNLOAD_CSV_TEMPLATE_FAILED = 'COMPANY_USER_DOWNLOAD_CSV_TEMPLATE_FAILED';
export const COMPANY_USER_DOWNLOAD_CSV_TEMPLATE_CLEAN = 'COMPANY_USER_DOWNLOAD_CSV_TEMPLATE_CLEAN';

export const LOGIN_AS = 'LOGIN_AS';
export const LOGIN_AS_START = 'LOGIN_AS_START';
export const LOGIN_AS_SUCCESS = 'LOGIN_AS_SUCCESS';
export const LOGIN_AS_FAILED = 'LOGIN_AS_FAILED';

export const SWITCH_USER = 'SWITCH_USER';
export const SWITCH_USER_START = 'SWITCH_USER_START';
export const SWITCH_USER_SUCCESS = 'SWITCH_USER_SUCCESS';
export const SWITCH_USER_FAILED = 'SWITCH_USER_FAILED';

export const BRANCH_USER_IMPORT = 'BRANCH_USER_IMPORT';
export const BRANCH_USER_IMPORT_START = 'BRANCH_USER_IMPORT_START';
export const BRANCH_USER_IMPORT_SUCCESS = 'BRANCH_USER_IMPORT_SUCCESS';
export const BRANCH_USER_IMPORT_FAILED = 'BRANCH_USER_IMPORT_FAILED';
export const BRANCH_USER_IMPORT_CLEAN = 'BRANCH_USER_IMPORT_CLEAN';

export const BRANCH_USER_EXPORT = 'BRANCH_USER_EXPORT';
export const BRANCH_USER_EXPORT_START = 'BRANCH_USER_EXPORT_START';
export const BRANCH_USER_EXPORT_SUCCESS = 'BRANCH_USER_EXPORT_SUCCESS';
export const BRANCH_USER_EXPORT_FAILED = 'BRANCH_USER_EXPORT_FAILED';
export const BRANCH_USER_EXPORT_CLEAN = 'BRANCH_USER_EXPORT_CLEAN';

export const BUSINESS_USER_IMPORT = 'BUSINESS_USER_IMPORT';
export const BUSINESS_USER_IMPORT_START = 'BUSINESS_USER_IMPORT_START';
export const BUSINESS_USER_IMPORT_SUCCESS = 'BUSINESS_USER_IMPORT_SUCCESS';
export const BUSINESS_USER_IMPORT_FAILED = 'BUSINESS_USER_IMPORT_FAILED';
export const BUSINESS_USER_IMPORT_CLEAN = 'BUSINESS_USER_IMPORT_CLEAN';

export const BUSINESS_USER_EXPORT = 'BUSINESS_USER_EXPORT';
export const BUSINESS_USER_EXPORT_START = 'BUSINESS_USER_EXPORT_START';
export const BUSINESS_USER_EXPORT_SUCCESS = 'BUSINESS_USER_EXPORT_SUCCESS';
export const BUSINESS_USER_EXPORT_FAILED = 'BUSINESS_USER_EXPORT_FAILED';
export const BUSINESS_USER_EXPORT_CLEAN = 'BUSINESS_USER_EXPORT_CLEAN';

export const INVITE_USERS = 'INVITE_USERS';
export const INVITE_USERS_START = 'INVITE_USERS_START';
export const INVITE_USERS_SUCCESS = 'INVITE_USERS_SUCCESS';
export const INVITE_USERS_FAILED = 'INVITE_USERS_FAILED';
export const INVITE_USERS_CLEAN = 'INVITE_USERS_CLEAN';
